version: '3'

services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: django_sandbox
    ports: 
      - "5432:5432"

  web:
    build: .
    image: alejandro17/django_sandbox:0.0.0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db